# Generated by Django 4.2.7 on 2023-11-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_posts_delete_fpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/images'),
        ),
    ]
