# Generated by Django 4.2.7 on 2023-11-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_posts_images_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
